trigger:
  branches:
    include:
      - backbenchers2024_backend_main  # Replace with your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: 'backbenchers2023'  
    dockerfile: 'Dockerfile'  
    containerRegistry: 'docker-hub-connection'  
    tags: 'backbenchers2023:latest'
